# Build and deploy the Hugo site.
image: archlinux
packages:
  - git
  - hugo
  - go
  - openssh
  - python-docutils
  - python-pygments
  - rsync
  - rubygems
sources:
  - https://git.sr.ht/~sumner/sumnerevans.com
  - https://github.com/sumnerevans/hugo.git
secrets:
  # SSH Known Hosts
  - a9b7dc2e-293f-4fea-aec7-618689d4e5f2
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
environment:
  REPO_NAME: sumnerevans.com
# triggers:
#   - action: email
#     condition: failure
#     to: ~sumner/public-inbox@lists.sr.ht
artifacts:
  - sumnerevans.com/public
tasks:
  # Use my fork of Hugo that correctly formats Math.
  # TODO: remove this step after https://github.com/gohugoio/hugo/pull/7763 is
  # merged.
  - build_hugo: |
      cd hugo
      go build

  - setup: |
      gem install scss
      echo "cd $REPO_NAME" >> ~/.buildenv

  - build: |
      ../hugo/hugo

  # Copy the website over to the server
  - rsync: |
      git branch --contains | grep master &&
        ssh root@deploy.sumnerevans.com "mkdir -p /var/www/sumnerevans.com" &&
        rsync -vr --delete-after public/ root@deploy.sumnerevans.com:/var/www/sumnerevans.com &&
        echo "Deploy complete" || echo "Skipping deploy since not on master"
