# Build and deploy the Hugo site.
image: nixos/unstable
secrets:
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
environment:
  REPO_NAME: sumnerevans.com
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
tasks:
  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  # let Nix do it's thing during this stage so the next ones are fast
  - nix-shell-env: |
      time nix-shell \
        --arg forWebsiteBuild true \
        --command "echo nix-shell environment is cached"

  - openring: |
      time nix-shell \
        --arg forWebsiteBuild true \
        --command "openring -S feed_urls.txt \
                             < resources/other-feeds.html.tmpl \
                             > themes/smol/layouts/partials/webring.html"

  - hugo: |
      time nix-shell \
        --arg forWebsiteBuild true \
        --command "hugo --verbose --gc --minify"

  - rsync: |
      # Skip if not on master
      git branch --contains | grep master || echo "Skipping deploy since not on master"
      git branch --contains | grep master || complete-build

      ssh-keyscan morak.sumnerevans.com >> ~/.ssh/known_hosts

      # Copy the website over to the server
      ssh root@morak.sumnerevans.com "mkdir -p /var/www/sumnerevans.com"
      time rsync -vr --delete-after public/ root@morak.sumnerevans.com:/var/www/sumnerevans.com
