# Build and deploy the Hugo site.
image: nixos/unstable
packages:
  - nixos.openssh
  - nixos.rsync
sources:
  - https://git.sr.ht/~sumner/sumnerevans.com
secrets:
  # SSH Known Hosts
  - 5f8876fe-b2b7-44f8-8ad5-6fa9bffbc52a
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
environment:
  REPO_NAME: sumnerevans.com
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
tasks:
  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  - build: |
      nix-channel --update
      nix-shell --command "hugo --gc --minify"

  - rsync: |
      # Skip if not on master
      git branch --contains | grep master || echo "Skipping deploy since not on master"
      git branch --contains | grep master || complete-build

      # Copy the website over to the server
      ssh root@bespin.sumnerevans.com "mkdir -p /var/www/sumnerevans.com"
      rsync -vr --delete-after public/ root@bespin.sumnerevans.com:/var/www/sumnerevans.com
