# Build and deploy the Hugo site.
image: archlinux
packages:
  - git
  - hugo
  - go
  - openssh
  - python-docutils
  - python-pygments
  - rsync
sources:
  - https://git.sr.ht/~sumner/sumnerevans.com
  - https://github.com/sumnerevans/hugo.git
secrets:
  # SSH Known Hosts
  - 5f8876fe-b2b7-44f8-8ad5-6fa9bffbc52a
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
environment:
  REPO_NAME: sumnerevans.com
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
tasks:
  # Use my fork of Hugo that correctly formats Math.
  # TODO: remove this step after https://github.com/gohugoio/hugo/pull/7763 is
  # merged.
  - build_hugo: |
      cd hugo
      go build --tags extended  # need extended support for SCSS

  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  - build: |
      ../hugo/hugo --gc --minify

  - rsync: |
      # Skip if not on master
      git branch --contains | grep master || echo "Skipping deploy since not on master"
      git branch --contains | grep master || complete-build

      # Copy the website over to the server
      ssh root@bespin.sumnerevans.com "mkdir -p /var/www/sumnerevans.com"
      rsync -vr --delete-after public/ root@bespin.sumnerevans.com:/var/www/sumnerevans.com
