image: python:3.6-alpine

# Build the pelican site
pelican:
  stage: build
  before_script:
    - ./cicd/pelican/before_script.sh
  script:
    - ./cicd/pelican/script.sh
  artifacts:
    paths:
      - output

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - ./cicd/deploy/before_script.sh
  script:
    - ./cicd/deploy/script.sh
