# Build the pelican site
pelican:
  image: python:3.6-alpine
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - ./cicd/pelican/before_script.sh
  script:
    - ./cicd/pelican/script.sh
  artifacts:
    paths:
      - output

deploy:
  image: alpine
  stage: deploy
  only:
    - master
  before_script:
    - ./cicd/deploy/before_script.sh
  script:
    - ./cicd/deploy/script.sh
