# Build and deploy the pelican site.
pages:
  image: python:3.6-alpine
  stage: deploy
  only:
    - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apk update && apk upgrade && apk add git make nodejs nodejs-npm
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - npm install -g sass
  script:
    - make publish
  artifacts:
    paths:
      - public
