language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
# this tests to make sure that it builds properly
- make publish

# Deploy to GitHub Pages.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHN1bW5lciUzQW1hdHJpeC5vcmcvJTIxTWFoekVncmlqQlJhTVFMQlJTJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
