language: python
addons:
  ssh_known_hosts: sumnerevans.com
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make publish
deploy:
  skip_cleanup: true
  provider: script
  script:
- openssl aes-256-cbc -K $encrypted_f058d753363d_key -iv $encrypted_f058d753363d_iv
  -in sws_deploy_rsa.enc -out sws_deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_sws_deploy_rsa
- ssh-add travis_sws_deploy_rsa
- ssh -i travis_sws_deploy_rsa sumnerevans@sumnerevans.com ls
- make deploy
on:
  branch: master
