language: python
addons:
  ssh_known_hosts: sumnerevans.com
python:
- 3.6
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_f058d753363d_key -iv $encrypted_f058d753363d_iv -in sws_deploy_rsa.enc -out sws_deploy_rsa -d
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make publish
- test $TRAVIS_BRANCH = "master" && make deploy
