baseURL = "https://sumnerevans.com"
languageCode = "en-us"
title = "Sumner Evans"
theme = "smol"

pygmentsCodefences = true
pygmentsStyle = "github"
pygmentsUseClasses = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

Paginate = 15

[minify]
  minifyOutput = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[params]
  author = "Sumner Evans"
  description = "I'm a Software Engineer at Beeper and an Adjunct Professor at Colorado School of Mines. This is my personal website, portfolio, and blog."
  title = "Sumner Evans"
  subtitle = "Software Engineer at Beeper"
  dateFmt = "2006-01-02"
  logo = "profile.jpg"

  # Theme
  themeColorAutoDetectBrowserPreference = true
  themeColor = 'dark'

  # Posts shown in homepage
  mainSections = ["posts"]

  # Isso
  # issoUrl = "//comments.sumnerevans.com"

  [params.issoOptions]
    avatar = false
    gravatar = true
    reply-notifications = true
    reply-to-self = true

  # Plausible
  [params.plausible]
    domain = "sumnerevans.com"
    plausibleRoot = "https://plausible.io"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 3

  [[menu.main]]
    identifier = "gear"
    name = "Gear"
    url = "/gear/"
    weight = 4

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 5

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 6

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 7

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 8

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 9

# Footer
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sumnerevans"
    weight = 1

  [[menu.footer]]
    name = "GitLab"
    url = "https://gitlab.com/sumner"
    weight = 2

  [[menu.footer]]
    name = "sourcehut"
    url = "https://sr.ht/~sumner"
    weight = 3

  [[menu.footer]]
    name = "Twitch"
    url = "https://www.twitch.tv/sumnerevans"
    weight = 4

  [[menu.footer]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCyrdRO4oJRpszr0ovN1FwBA"
    weight = 5

  [[menu.footer]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/2319844/sumner-evans"
    weight = 6

  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/sumner_evans"
    weight = 7

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/sumnerevans"
    weight = 8

  [[menu.footer]]
    name = "Liberapay"
    url = "https://liberapay.com/sumner"
    weight = 9
