baseURL = "https://sumnerevans.com"
languageCode = "en-us"
title = "Sumner Evans"
theme = "smol"
summaryLength = 60

pygmentsCodefences = true
pygmentsStyle = "github"
pygmentsUseClasses = true

timeout = "360s"

[outputs]
  home = ["HTML", "RSS", "JSON", "HASH"]

[outputFormats]
  [outputFormats.hash]
    isPlainText = true
    mediaType = 'text/plain+sha256'
    notAlternative = true

[mediaTypes]
  [mediaTypes.'text/plain+sha256']
    suffixes = ['sha256']

# paginate = 15

[minify]
  minifyOutput = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[imaging]
  quality = 90

[privacy]
  [privacy.youTube]
    privacyEnhanced = true

[params]
  author = "Sumner Evans"
  description = "I'm a Senior Implementation Tech Lead at Can/Am Technologies. This is my personal website, portfolio, and blog."
  title = "Sumner Evans"
  subtitle = "Senior Implementation Tech Lead at Can/Am Technologies"
  dateFmt = "2006-01-02"
  logo = "profile.jpg"

  # Theme
  themeColorAutoDetectBrowserPreference = true
  themeColor = 'dark'

  # Posts shown in homepage
  mainSections = ["posts"]

  # Isso
  issoUrl = "comments.sumnerevans.com"

  [params.goatcounter]
    domain = "https://sws.goatcounter.com/count"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 2

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 5

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 6

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 7

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 8

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 9

# Footer
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sumnerevans"
    weight = 1

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/sumnerevans"
    weight = 2

  [[menu.footer]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCyrdRO4oJRpszr0ovN1FwBA"
    weight = 5

  [[menu.footer]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/2319844/sumner-evans"
    weight = 6

[related]
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = 'keywords'
    type = 'basic'
    weight = 100
  [[related.indices]]
    name = 'tags'
    type = 'basic'
    weight = 60
  [[related.indices]]
    name = 'categories'
    type = 'basic'
    weight = 30
  [[related.indices]]
    name = 'date'
    type = 'basic'
    weight = 10
