name: "Build and Deploy"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: "recursive"
      - uses: nixbuild/nix-quick-install-action@v25
      - uses: cachix/cachix-action@v12
        with:
          name: sumnerevans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Cache nix shell environment
        run: |
          nix develop '.#ci' \
            --command bash -c 'echo nix build environment cached'

      - name: Webring
        run: |
          nix develop '.#ci' \
            --command bash -c "openring -S feed_urls.txt \
                -n 6 -l 100 \
                < resources/other-feeds.html.tmpl \
                > themes/smol/layouts/partials/webring.html"

      - name: Hugo
        run: |
          nix develop '.#ci' \
            --command bash -c "hugo --verbose --gc --minify"

      - name: rsync
        if: github.ref == 'refs/heads/master'
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: morak.sumnerevans.com
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SOURCE: ./public/
          TARGET: /var/www/sumnerevans.com
          VERBOSE: true
