name: "Build and Deploy"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: "recursive"
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: sumnerevans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Cache nix shell environment
        run: nix-shell
          --arg forWebsiteBuild true
          --run "echo nix-shell environment is cached"

      - name: Webring
        run: nix-shell
          --arg forWebsiteBuild true
          --run "openring -S feed_urls.txt
                  -n 6
                  -l 100
                  < resources/other-feeds.html.tmpl
                  > themes/smol/layouts/partials/webring.html"

      - name: Hugo
        run: nix-shell
          --arg forWebsiteBuild true
          --run "hugo --verbose --gc --minify"

      - name: rsync
        if: github.ref == 'refs/heads/master'
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: morak.sumnerevans.com
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SOURCE: ./public/
          TARGET: /var/www/sumnerevans.com
          VERBOSE: true
