name: "Build and Deploy"

on:
  pull_request:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: DeterminateSystems/nix-installer-action@v10

      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - uses: DeterminateSystems/flake-checker-action@v7
        with:
          fail-mode: true

      - name: Cache nix shell environment
        run: |
          nix develop '.#ci' \
            --command bash -c 'echo nix build environment cached'

      - name: Webring
        run: |
          nix develop '.#ci' \
            --command bash -c "openring -S feed_urls.txt \
                -n 6 -l 100 \
                < resources/other-feeds.html.tmpl \
                > themes/smol/layouts/partials/webring.html"

      - name: Hugo
        run: |
          nix develop '.#ci' \
            --command bash -c "hugo --verbose --gc --minify"

      - name: Teaching raw HTML
        run: |
          rm -rf public/teaching/csci400-s19
          rm -rf public/teaching/csci564-s21
          cp -r content/teaching/csci400-s19 public/teaching
          cp -r content/teaching/csci564-s21 public/teaching

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
